version: '2.0'

services:
  auth:
    build: internal/auth/.
    command: ./auth-service
    ports:
      - 8080:8080
    depends_on:
      - db-auth

  db-auth:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PSWD}"
    volumes:
      - ./internal/auth/schema/:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
    - 5432:5432
