version: '3.9'

services:
  user-data:
    build:
      context: .
      dockerfile: ./deployments/user_data.Dockerfile
    environment:
      DATABASE_URL: "user=service password=test host=db-user-data port=5432 dbname=persons"
#      DATABASE_URL: "postgresql://db-user-data/persons?user=service&password=secret"
    command: ./user-data-service
    ports:
      - 8086:8086
    depends_on:
      - db-user-data

  chat-diff-service:
    build: internal/chat_diff/.
    command: ./chat-diff-service
    ports:
      - 8081:8081
    depends_on:
      - message-core

  flusher-service:
    build: internal/flusher/.
    command: ./flusher-service
    ports:
      - 8082:8082
    depends_on:
      - message-core
      - mongo-all

  chat-history-service:
    build: internal/chat/.
    command: ./chat-history-service
    ports:
      - 8083:8083
    depends_on:
      - message-core
      - mongo-all

  chat-list-service:
    build: internal/chat_list/.
    command: ./chat-list-service
    ports:
      - 8084:8084
    depends_on:
      - message-core
      - mongo-all

  mongo-all:
    image: mongo
    ports:
      - 27017:27017

  db-user-data:
    image: postgres:13.3
    environment:
      POSTGRES_DB: persons
      POSTGRES_USER: service
      POSTGRES_PASSWORD: test
    volumes:
      - ./internal/user_data/db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 5432:5432
