version: '3.9'

services:
  message-core:
    build:
      context: .
      dockerfile: deployments/message_core.Dockerfile
    ports:
      - 3301:3301

  chat-diff:
    build:
      context: .
      dockerfile: deployments/chat_diff.Dockerfile
    environment:
      CHAT_DIFF_CONFIG: configs/.
    command: ./chat-diff-service
    ports:
      - 8081:8081
    depends_on:
      - message-core

  flusher:
    build:
      context: .
      dockerfile: deployments/flusher.Dockerfile
    command: ./flusher-service
    environment:
      FLUSHER_CONFIG: configs/.
      DATABASE_URL: "user=service password=test host=db-chat port=5432 dbname=chats"
    ports:
      - 8082:8082
    depends_on:
      - message-core
      - db-chat

  chat:
    build:
      context: .
      dockerfile: deployments/chat.Dockerfile
    command: ./chat-service
    environment:
      CHAT_CONFIG: configs/.
      DATABASE_URL: "user=service password=test host=db-chat port=5432 dbname=chats"
      DATABASE_ALTERNATIVE_URL: "postgresql://db-chat:5432/chats?user=service&password=test"
      JWT_SIGNED_KEY: "test"
    ports:
      - 8083:8083
    depends_on:
      - message-core
      - db-chat

  peer:
    build:
      context: .
      dockerfile: deployments/peer.Dockerfile
    command: ./peer-service
    environment:
      PEER_CONFIG: configs/.
    ports:
      - 8084:8084
    depends_on:
      - message-core

  user-data:
    build:
      context: .
      dockerfile: ./deployments/user_data.Dockerfile
    environment:
      USER_DATA_CONFIG: configs/.
      JWT_SIGNED_KEY: "test"
      DATABASE_URL: "user=service password=test host=db-user-data port=5432 dbname=users"
    command: ./user-data-service
    ports:
      - 8086:8086
    depends_on:
      - db-user-data

  db-user-data:
    image: postgres:13.3
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: service
      POSTGRES_PASSWORD: test
    volumes:
      - ./internal/user_data/db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 5432:5432

  db-chat:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "chats"
      POSTGRES_USER: "service"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./internal/chat/db/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 5433:5432

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./configs/:/etc/nginx/conf.d/
      - ./temp/dist/:/var/www/html/dist/
    depends_on:
      - user-data
      - peer