definitions:
  internal_delivery.Error:
    properties:
      message:
        type: string
    type: object
  models.User:
    properties:
      name:
        type: string
      nickname:
        type: string
      password:
        type: string
      surname:
        type: string
      user_id:
        type: string
    type: object
  our-little-chatik_internal_gateway_internal_delivery.Error:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/gateway/logout:
    delete:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_delivery.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_delivery.Error'
      summary: Log out a user
  /api/gateway/search:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_delivery.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_delivery.Error'
      summary: Find a user
  /api/gateway/signin:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_delivery.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_delivery.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_delivery.Error'
      summary: Sign in a user
  /api/gateway/signup:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_delivery.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_delivery.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_delivery.Error'
      summary: Sign up a user
swagger: "2.0"
