name: Common tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Unit tests
        run: go mod download && go mod tidy && make unit

      - name: Quality Gate - Test coverage shall be above threshold
        env:
          TESTCOVERAGE_THRESHOLD: 20
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi
      - name: Coverage evaluation
        run: |
          go test ./... -short -coverprofile coverage.out
          echo "COVERAGE=`go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]{2}'`" >> $GITHUB_ENV
          echo $COVERAGE
      - uses: kevinfjiang/coverage-badge@v1
        with:
          coverage: ${{ env.COVERAGE }}
          change_file: ./README.md
          style: flat
          color: yellow
