name: Common tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Unit tests
        run: go mod download && go mod tidy && make unit