name: Build and push images
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
        - ./deployments/chat.Dockerfile
        - ./deployments/users.Dockerfile
        - ./deployments/peer.Dockerfile
        - ./deployments/flusher.Dockerfile
        - ./deployments/call.Dockerfile
        - ./deployments/nginx.Dockerfile
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: vr0009/our-little-chat

      - name: Build and push chat service image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
